config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :products do
    resource :purchase
  end

  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :amount)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :description, class: 'form-label' %>
      <%= form.text_area :description, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :amount, class: 'form-label' %>
      <%= form.number_field :amount, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <% if product.persisted? %>
      <div class="float-end">
        <%= link_to 'Destroy', product, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if product.persisted? %>
      <%= link_to "Cancel", product, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", products_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= product.amount %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form', product: @product %>

app/views/products/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Products</h1>
  </div>

  <div class="col-sm-6 text-end">
  <%= link_to new_product_path, class: 'btn btn-primary' do %>
    Add New Product
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    
        <th>Name</th>
    

            <th>Description</th>
            <th>Amount</th>
            
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <%= content_tag :tr, id: dom_id(product), class: dom_class(product) do %>
          
            <td><%= link_to product.name, product %></td>
          

                      <td><%= product.description %></td>
                      <td><%= formatted_amount product.amount %></td>
          
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form', product: @product %>

app/views/products/show.html.erb
<div class="page-header">
  <%= link_to products_path, class: 'btn btn-default' do %>
    All Products
  <% end %>
  <%= link_to edit_product_path(@product), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show product</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @product.name %></dd>
  <dt>Description:</dt>
  <dd><%= @product.description %></dd>
  <dt>Amount:</dt>
  <dd><%= formatted_amount @product.amount %></dd>
</dl>

<%= link_to "Purchase", product_purchase_path(@product, class: "btn btn-primary")%>